AWSTemplateFormatVersion: '2010-09-09'
Description: 'Qualys QScanner for AWS CodeBuild - Multi-Region StackSet Template'

Parameters:
  ScanType:
    Type: String
    Description: Type of scan to perform
    AllowedValues:
      - container
      - code
    Default: container

  QualysPod:
    Type: String
    Description: Qualys platform POD
    AllowedValues:
      - US1
      - US2
      - US3
      - US4
      - EU1
      - EU2
      - CA1
      - IN1
      - AU1
      - UK1
      - AE1
      - KSA1
    Default: US1

  QualysAccessToken:
    Type: String
    Description: Qualys API access token
    NoEcho: true

  EnableReportBucket:
    Type: String
    Description: Create S3 bucket for scan reports
    AllowedValues:
      - 'true'
      - 'false'
    Default: 'true'

  EnableSecurityHub:
    Type: String
    Description: Enable Security Hub integration
    AllowedValues:
      - 'true'
      - 'false'
    Default: 'false'

Conditions:
  CreateReportBucket: !Equals [!Ref EnableReportBucket, 'true']
  IsContainerScan: !Equals [!Ref ScanType, 'container']
  IsCodeScan: !Equals [!Ref ScanType, 'code']
  EnableSecurityHubIntegration: !Equals [!Ref EnableSecurityHub, 'true']

Resources:
  KMSKey:
    Type: AWS::KMS::Key
    Properties:
      Description: KMS key for Qualys CodeBuild resources
      EnableKeyRotation: true
      KeyPolicy:
        Version: '2012-10-17'
        Statement:
          - Sid: AllowRootAccess
            Effect: Allow
            Principal:
              AWS: !Sub 'arn:aws:iam::${AWS::AccountId}:root'
            Action: 'kms:*'
            Resource: '*'
          - Sid: AllowSecretsManagerAccess
            Effect: Allow
            Principal:
              Service: secretsmanager.amazonaws.com
            Action:
              - kms:Encrypt
              - kms:Decrypt
              - kms:GenerateDataKey*
            Resource: '*'
            Condition:
              StringEquals:
                kms:CallerAccount: !Ref AWS::AccountId

  KMSKeyAlias:
    Type: AWS::KMS::Alias
    Properties:
      AliasName: !Sub 'alias/qualys-codebuild-${AWS::Region}'
      TargetKeyId: !Ref KMSKey

  QualysSecret:
    Type: AWS::SecretsManager::Secret
    Properties:
      Name: !Sub 'qualys-codebuild-${AWS::Region}-credentials'
      Description: Qualys API credentials for QScanner
      KmsKeyId: !Ref KMSKey
      SecretString: !Sub |
        {
          "accessToken": "${QualysAccessToken}",
          "pod": "${QualysPod}"
        }

  LoggingBucket:
    Type: AWS::S3::Bucket
    Condition: CreateReportBucket
    Metadata:
      checkov:
        skip:
          - id: CKV_AWS_18
            comment: Logging bucket cannot log to itself
    DeletionPolicy: Retain
    UpdateReplacePolicy: Retain
    Properties:
      BucketName: !Sub 'qualys-codebuild-logs-${AWS::AccountId}-${AWS::Region}'
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256
      VersioningConfiguration:
        Status: Enabled
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      LifecycleConfiguration:
        Rules:
          - Id: DeleteOldLogs
            Status: Enabled
            ExpirationInDays: 30
            NoncurrentVersionExpiration:
              NoncurrentDays: 7
      OwnershipControls:
        Rules:
          - ObjectOwnership: BucketOwnerPreferred

  LoggingBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Condition: CreateReportBucket
    Properties:
      Bucket: !Ref LoggingBucket
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Sid: S3ServerAccessLogsPolicy
            Effect: Allow
            Principal:
              Service: logging.s3.amazonaws.com
            Action: s3:PutObject
            Resource: !Sub '${LoggingBucket.Arn}/*'
            Condition:
              ArnLike:
                aws:SourceArn: !Sub 'arn:aws:s3:::qualys-codebuild-reports-${AWS::AccountId}-${AWS::Region}'
              StringEquals:
                aws:SourceAccount: !Ref AWS::AccountId

  ReportBucket:
    Type: AWS::S3::Bucket
    Condition: CreateReportBucket
    DependsOn: LoggingBucketPolicy
    DeletionPolicy: Retain
    UpdateReplacePolicy: Retain
    Properties:
      BucketName: !Sub 'qualys-codebuild-reports-${AWS::AccountId}-${AWS::Region}'
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256
      VersioningConfiguration:
        Status: Enabled
      LoggingConfiguration:
        DestinationBucketName: !Ref LoggingBucket
        LogFilePrefix: report-bucket-logs/
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      LifecycleConfiguration:
        Rules:
          - Id: DeleteOldReports
            Status: Enabled
            ExpirationInDays: 90
            NoncurrentVersionExpiration:
              NoncurrentDays: 30

  CodeBuildRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: codebuild.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: BasePolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - logs:CreateLogGroup
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                Resource:
                  - !Sub 'arn:aws:logs:${AWS::Region}:${AWS::AccountId}:log-group:/aws/codebuild/qualys-codebuild-*'
              - Effect: Allow
                Action:
                  - secretsmanager:GetSecretValue
                Resource:
                  - !Ref QualysSecret
              - Effect: Allow
                Action:
                  - codebuild:CreateReportGroup
                  - codebuild:CreateReport
                  - codebuild:UpdateReport
                  - codebuild:BatchPutTestCases
                  - codebuild:BatchPutCodeCoverages
                Resource:
                  - !Sub 'arn:aws:codebuild:${AWS::Region}:${AWS::AccountId}:report-group/qualys-codebuild-*'
        - !If
          - CreateReportBucket
          - PolicyName: S3Policy
            PolicyDocument:
              Version: '2012-10-17'
              Statement:
                - Effect: Allow
                  Action:
                    - s3:PutObject
                    - s3:GetObject
                  Resource:
                    - !Sub '${ReportBucket.Arn}/*'
                - Effect: Allow
                  Action:
                    - s3:ListBucket
                  Resource:
                    - !GetAtt ReportBucket.Arn
          - !Ref AWS::NoValue
        - !If
          - EnableSecurityHubIntegration
          - PolicyName: SecurityHubPolicy
            PolicyDocument:
              Version: '2012-10-17'
              Statement:
                - Effect: Allow
                  Action:
                    - securityhub:BatchImportFindings
                  Resource: '*'
          - !Ref AWS::NoValue
        - !If
          - IsContainerScan
          - PolicyName: ECRPolicy
            PolicyDocument:
              Version: '2012-10-17'
              Statement:
                - Effect: Allow
                  Action:
                    - ecr:GetAuthorizationToken
                  Resource: '*'
                - Effect: Allow
                  Action:
                    - ecr:BatchCheckLayerAvailability
                    - ecr:GetDownloadUrlForLayer
                    - ecr:BatchGetImage
                  Resource: '*'
          - !Ref AWS::NoValue

  ContainerScanProject:
    Type: AWS::CodeBuild::Project
    Condition: IsContainerScan
    Properties:
      Name: !Sub 'qualys-codebuild-container-${AWS::Region}'
      Description: Qualys container scanning
      ServiceRole: !GetAtt CodeBuildRole.Arn
      Artifacts:
        Type: NO_ARTIFACTS
      Environment:
        Type: LINUX_CONTAINER
        ComputeType: BUILD_GENERAL1_SMALL
        Image: aws/codebuild/amazonlinux2-x86_64-standard:5.0
        PrivilegedMode: true
        EnvironmentVariables:
          - Name: QUALYS_POD
            Value: !Ref QualysPod
          - Name: QUALYS_SECRET_ARN
            Value: !Ref QualysSecret
          - Name: SCAN_MODE
            Value: get-report
          - Name: SCAN_TYPES
            Value: pkg,secret
          - Name: OUTPUT_DIR
            Value: qualys-reports
          - !If
            - CreateReportBucket
            - Name: REPORT_BUCKET
              Value: !Ref ReportBucket
            - !Ref AWS::NoValue
          - !If
            - EnableSecurityHubIntegration
            - Name: SEND_TO_SECURITY_HUB
              Value: 'true'
            - !Ref AWS::NoValue
      Source:
        Type: NO_SOURCE
        BuildSpec: |
          version: 0.2
          env:
            secrets-manager:
              QUALYS_ACCESS_TOKEN: ${QUALYS_SECRET_ARN}:accessToken
          phases:
            pre_build:
              commands:
                - |
                  QSCANNER_DIR="/tmp/qscanner"
                  QSCANNER_URL="https://github.com/nelssec/qualys-lambda/raw/main/scanner-lambda/qscanner.gz"
                  QSCANNER_SHA256="1a31b854154ee4594bb94e28aa86460b14a75687085d097f949e91c5fd00413d"
                  mkdir -p $QSCANNER_DIR
                  curl -sL $QSCANNER_URL -o $QSCANNER_DIR/qscanner.gz
                  echo "$QSCANNER_SHA256 $QSCANNER_DIR/qscanner.gz" | sha256sum -c -
                  gunzip -f $QSCANNER_DIR/qscanner.gz
                  chmod +x $QSCANNER_DIR/qscanner
            build:
              commands:
                - mkdir -p $OUTPUT_DIR
                - |
                  /tmp/qscanner/qscanner \
                    --pod $QUALYS_POD \
                    --mode $SCAN_MODE \
                    --scan-types $SCAN_TYPES \
                    --format json,sarif \
                    --report-format sarif,json \
                    --output-dir $OUTPUT_DIR \
                    image $IMAGE_ID
            post_build:
              commands:
                - |
                  if [ -n "$REPORT_BUCKET" ]; then
                    TIMESTAMP=$(date -u +"%Y-%m-%dT%H-%M-%SZ")
                    aws s3 cp $OUTPUT_DIR/ s3://$REPORT_BUCKET/$CODEBUILD_BUILD_PROJECT/$TIMESTAMP/ --recursive --include "*.json"
                  fi
          reports:
            qualys-sarif:
              files:
                - '**/*-Report.sarif.json'
              base-directory: qualys-reports
              file-format: SARIFZIP
      TimeoutInMinutes: 30

  CodeScanProject:
    Type: AWS::CodeBuild::Project
    Condition: IsCodeScan
    Properties:
      Name: !Sub 'qualys-codebuild-code-${AWS::Region}'
      Description: Qualys code/SCA scanning
      ServiceRole: !GetAtt CodeBuildRole.Arn
      Artifacts:
        Type: NO_ARTIFACTS
      Environment:
        Type: LINUX_CONTAINER
        ComputeType: BUILD_GENERAL1_SMALL
        Image: aws/codebuild/amazonlinux2-x86_64-standard:5.0
        PrivilegedMode: false
        EnvironmentVariables:
          - Name: QUALYS_POD
            Value: !Ref QualysPod
          - Name: QUALYS_SECRET_ARN
            Value: !Ref QualysSecret
          - Name: SCAN_MODE
            Value: get-report
          - Name: SCAN_TYPES
            Value: pkg,secret
          - Name: OUTPUT_DIR
            Value: qualys-reports
          - !If
            - CreateReportBucket
            - Name: REPORT_BUCKET
              Value: !Ref ReportBucket
            - !Ref AWS::NoValue
          - !If
            - EnableSecurityHubIntegration
            - Name: SEND_TO_SECURITY_HUB
              Value: 'true'
            - !Ref AWS::NoValue
      Source:
        Type: NO_SOURCE
        BuildSpec: |
          version: 0.2
          env:
            secrets-manager:
              QUALYS_ACCESS_TOKEN: ${QUALYS_SECRET_ARN}:accessToken
          phases:
            pre_build:
              commands:
                - |
                  QSCANNER_DIR="/tmp/qscanner"
                  QSCANNER_URL="https://github.com/nelssec/qualys-lambda/raw/main/scanner-lambda/qscanner.gz"
                  QSCANNER_SHA256="1a31b854154ee4594bb94e28aa86460b14a75687085d097f949e91c5fd00413d"
                  mkdir -p $QSCANNER_DIR
                  curl -sL $QSCANNER_URL -o $QSCANNER_DIR/qscanner.gz
                  echo "$QSCANNER_SHA256 $QSCANNER_DIR/qscanner.gz" | sha256sum -c -
                  gunzip -f $QSCANNER_DIR/qscanner.gz
                  chmod +x $QSCANNER_DIR/qscanner
            build:
              commands:
                - mkdir -p $OUTPUT_DIR
                - |
                  /tmp/qscanner/qscanner \
                    --pod $QUALYS_POD \
                    --mode $SCAN_MODE \
                    --scan-types $SCAN_TYPES \
                    --format json,sarif \
                    --report-format sarif,json \
                    --output-dir $OUTPUT_DIR \
                    repo ${SCAN_PATH:-.}
            post_build:
              commands:
                - |
                  if [ -n "$REPORT_BUCKET" ]; then
                    TIMESTAMP=$(date -u +"%Y-%m-%dT%H-%M-%SZ")
                    aws s3 cp $OUTPUT_DIR/ s3://$REPORT_BUCKET/$CODEBUILD_BUILD_PROJECT/$TIMESTAMP/ --recursive --include "*.json"
                  fi
          reports:
            qualys-sarif:
              files:
                - '**/*-Report.sarif.json'
              base-directory: qualys-reports
              file-format: SARIFZIP
      TimeoutInMinutes: 30

Outputs:
  ProjectName:
    Description: CodeBuild project name
    Value: !If
      - IsContainerScan
      - !Ref ContainerScanProject
      - !Ref CodeScanProject

  SecretArn:
    Description: Secrets Manager secret ARN
    Value: !Ref QualysSecret

  ReportBucketName:
    Condition: CreateReportBucket
    Description: S3 bucket for scan reports
    Value: !Ref ReportBucket

  Region:
    Description: Deployed region
    Value: !Ref AWS::Region
